//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CellLocatiom.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CELLLOCATIOM_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_DLG_LOAD                    131
#define IDD_DLG_QRY                     132
#define IDC_CURSOR1                     134
#define IDB_BITMAP3                     135
#define IDB_BITMAP1                     136
#define IDB_BITMAP2                     137
#define IDR_MENU1                       139
#define IDD_DLG_REALTIME                140
#define IDD_DLG_MARK                    141
#define IDD_DLG_RST                     143
#define IDD_DLG_EDIT                    144
#define IDD_DLG_DOWN                    145
#define IDR_MENU2                       146
#define IDD_DLG_BS_LOAD                 147
#define IDR_MENU3                       148
#define IDR_MENU4                       149
#define IDR_MENU5                       152
#define IDR_MENU6                       153
#define IDD_DLG_PREVIEW                 154
#define IDR_MENU7                       155
#define IDR_MENU8                       156
#define IDC_LIST1                       1001
#define IDC_STATIC_TAB                  1002
#define IDC_LIST3                       1002
#define IDC_EXPLORER1                   1003
#define IDC_BUTTON1                     1005
#define IDC_CHECK1                      1006
#define IDC_BUTTON11                    1006
#define IDC_BUTTON3                     1007
#define IDC_BUTTON12                    1007
#define IDC_RADIO2                      1008
#define IDC_BUTTON13                    1008
#define IDC_BUTTON4                     1009
#define IDC_BUTTON14                    1009
#define IDC_COMBO1                      1010
#define IDC_BUTTON15                    1010
#define IDC_EDIT1                       1011
#define IDC_EDIT2                       1012
#define IDC_BUTTON2                     1013
#define IDC_RADIO1                      1014
#define IDC_BUTTON9                     1014
#define IDC_STATIC_GPS                  1015
#define IDC_RADIO4                      1015
#define IDC_EDIT6                       1015
#define IDC_STATIC_1                    1016
#define IDC_RADIO5                      1016
#define IDC_STATIC_2                    1017
#define IDC_RADIO6                      1017
#define IDC_STATIC_3                    1018
#define IDC_RADIO7                      1018
#define IDC_STATIC_LINK                 1019
#define IDC_BUTTON7                     1019
#define IDC_RADIO8                      1019
#define IDC_STATIC_TIME                 1020
#define IDC_BUTTON8                     1020
#define IDC_RADIO9                      1020
#define IDC_BUTTON5                     1021
#define IDC_RADIO10                     1021
#define IDC_BUTTON17                    1021
#define IDC_BUTTON6                     1022
#define IDC_RADIO12                     1022
#define IDC_BUTTON18                    1022
#define IDC_STATIC_INFO                 1023
#define IDC_STATIC_4                    1023
#define IDC_EDIT7                       1023
#define IDC_RADIO3                      1024
#define IDC_EDIT8                       1024
#define IDC_DATETIMEPICKER1             1025
#define IDC_DATETIMEPICKER2             1026
#define IDC_STATIC_5                    1027
#define IDC_CHECK3                      1027
#define IDC_BUTTON10                    1028
#define IDC_BUTTON16                    1029
#define IDC_STATIC_6                    1030
#define IDC_STATIC_REAL                 1031
#define IDC_STATIC_7                    1031
#define IDC_CHECK2                      1032
#define IDC_EDIT4                       1032
#define IDC_STATIC_CUR                  1033
#define IDC_EDIT3                       1034
#define IDC_STATIC_BOTTOM               1035
#define IDC_EDIT5                       1035
#define IDC_STATIC_MK                   1036
#define IDC_RADIO11                     1037
#define IDC_STATIC_HIS                  1038
#define IDC_LIST2                       1039
#define IDC_STATIC_LNG                  1040
#define IDC_LIST4                       1040
#define IDC_STATIC_LAT                  1041
#define IDC_STATIC1                     1042
#define IDC_STATIC2                     1043
#define IDC_COMBO2                      1044
#define IDC_STATIC3                     1045
#define IDC_STATIC_Local                1045
#define IDC_STATIC_K                    1046
#define IDC_STATIC_HL                   1047
#define IDC_STATIC_JLM1                 1048
#define IDC_STATIC_JLM2                 1049
#define IDC_STATIC_T1                   1049
#define IDC_STATIC_JLM3                 1050
#define IDC_STATIC_T2                   1050
#define IDC_STATIC_JLM4                 1051
#define IDC_STATIC_T3                   1051
#define IDC_STATIC_JLM5                 1052
#define IDC_STATIC_T4                   1052
#define IDC_LIST5                       1053
#define IDC_BTN_MAP_SWITCH              1054
#define IDC_STATIC_T5                   1055
#define IDC_DATETIMEPICKER3             1056
#define IDC_LIST8                       1059
#define ID_MENU_EXPORT                  32771
#define IDC_MENU_DEL                    32772
#define ID_MENU_DEL_CUR                 32773
#define ID_MENU_DEL_ALL                 32774
#define ID_REC_DELETE                   32775
#define MENU_LOCK_MODULE                32776
#define MENU_RELEASE_LOCK               32777
#define MENU_CHOOSE_CELL                32778
#define MENU_DELETE_CELL                32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
